#importar imagen base de python
FROM python:3.12-slim

#Crear en el contenedor Carpeta Trabajo

WORKDIR /app

#Copiar los requerimientos al contenedor
COPY requirements.txt .

#Instalamos las dependencias de FASTAPI
RUN pip install --no-cache-dir -r requirements.txt

#Copia el código del servidor
COPY ./app ./app

#Exponer el puerto de trabajo
EXPOSE 5000

#Comando a ejecutar levantar Servidor
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]



